services:
    apache:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: example-app
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3306:3306"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - "8081:80"
        networks:
            - laravel

    node:
        image: node:latest
        restart: always
        networks:
            - laravel
        volumes:
            - .:/var/app
        working_dir: /var/app/
        command: bash -c "npm install && npm run dev"
        healthcheck:
            test: ["CMD", "node", "-v"]
            interval: 30s
            timeout: 10s
            retries: 5

    composer:
        image: composer:latest
        restart: always
        networks:
            - laravel
        volumes:
            - .:/var/app
        working_dir: /var/app
        entrypoint: ["composer", "install", "--ignore-platform-reqs", "--no-scripts"]

networks:
    laravel:
        driver: bridge
